# .github/workflows/cd.yml
name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'YOUR_WORKLOAD_IDENTITY_PROVIDER' # Paste the value here
          service_account: 'YOUR_SERVICE_ACCOUNT' # e.g., github-actions-sa@your-project-id.iam.gserviceaccount.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker YOUR_REGION-docker.pkg.dev # e.g., us-central1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: YOUR_REGION-docker.pkg.dev/YOUR_PROJECT_ID/fraud-detection-service/fraud-model:${{ github.sha }}

      - name: Setup CML
        uses: iterative/setup-cml@v1
        
      - name: Post CML report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create --commit-sha ${{ github.sha }} "✅ Docker image built and pushed successfully to Artifact Registry with tag: `${{ github.sha }}`"
