# .github/workflows/cd.yml
name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/503062302911/locations/global/workloadIdentityPools/actions-pool-1/providers/github-provider' # Paste the value here
          service_account: 'github-actions-sa@rapid-spider-461505-b4.iam.gserviceaccount.com' # e.g., github-actions-sa@your-project-id.iam.gserviceaccount.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev # e.g., us-central1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: us-central1-docker.pkg.dev/rapid-spider-461505-b4/fraud-detection-service/fraud-model:${{ github.sha }}

      - name: Setup CML
        uses: iterative/setup-cml@v1
        
      - name: Post CML report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "✅ Docker image built and pushed successfully to Artifact Registry with tag: \`${{ github.sha }}\`" > report.md
          cml comment create report.md --commit-sha ${{ github.sha }}
